name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

concurrency: 
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保检出所有文件

      - name: Rename well-known to .well-known (if needed)
        run: |
          if [ -d "well-known" ]; then
            mv well-known .well-known
            echo "Renamed well-known to .well-known"
          else
            echo "Directory 'well-known' not found, skipping rename."
          fi

      - name: Upload artifact
        uses: dahisea/upload-pages-artifact@main
        with:
          path: "."  # 上传整个仓库（包括 .well-known）

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main
