name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
     pages: write
     id-token: write

concurrency: 
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        
      - uses: actions/upload-pages-artifact@main
        with:
          path: '.'

      - uses: actions/deploy-pages@main
