name: Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  pages: write
  id-token: write

concurrency: 
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # 确保检出所有文件，包括点文件和.well-known目录
          fetch-depth: 0

      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          # 明确包含.well-known目录
          path: |
            .well-known
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@main
